### ISSUE TITLE
[Bug]: 1.20.1 Forge craft start fails (Crafting Tree / ae2ct crash blocks TTC-in-tree)

### ISSUE THREAD

**Issue by cTux** [cTux/ae2-crafting-time#96]
**AE2 Crafting Time version:** 1.0.12 (dev build on `feat/ttc-smooth-grid-badges`)

**Minecraft version and mod loader:** Minecraft 1.20.1 - Forge (Forge 47.4.23)

**Modpack name:** custom / dev run (`run-1.20.1-Forge.bat`)

## What happened?

On 1.20.1 Forge, starting *any* craft fails. AE2 logs `Failed to start crafting job.` and the client chat shows:

```
java.lang.NoSuchMethodError: 'net.minecraft.network.FriendlyByteBuf net.minecraft.network.FriendlyByteBuf.m_130130_(int)'
```

(`m_130130_` is the obfuscated name of `FriendlyByteBuf.writeVarInt`.)

This blocks the whole "TTC in Crafting Tree" feature on 1.20.1 Forge, because the Crafting Tree window never opens — the craft itself can't start.

1.20.1 Fabric, 1.21.1 NeoForge, and 26.1.2 NeoForge all work. Only 1.20.1 Forge is broken.

## Root cause (downstream mod)

The crash is **not** in AE2 Crafting Time. The failing mixin is `ae2ct.mixins.json:AE2CraftingPlanSummary` from the **Crafting Tree** mod (`ae2ct-1.20.1-1.1.1.jar`), applied into `appeng.menu.me.crafting.CraftingPlanSummary` right before the failure. The debug log shows:

```
[Server thread/DEBUG] [mixin/]: Mixing AE2CraftingPlanSummary from ae2ct.mixins.json into appeng.menu.me.crafting.CraftingPlanSummary
[Server thread/DEBUG] [mixin/]: ae2ct.mixins.json:AE2CraftingPlanSummary: Class version 61 required is higher than the class version supported by the current version of Mixin (JAVA_8 supports class version 52)
[Server thread/WARN] [AE2:S/]: Failed to start crafting job.
[Render thread/INFO] [ChatComponent]: [System] [CHAT] Error: java.lang.NoSuchMethodError: '...FriendlyByteBuf.m_130130_(int)'
```

Our mod's mixins (`ae2craftingtime.mixins.json`) applied cleanly in the same window (no errors), and our code never calls `FriendlyByteBuf.writeVarInt` during craft start.

## How can we reproduce it?

1. Install AE2 + Crafting Tree `ae2ct-1.20.1-1.1.1` + AE2 Crafting Time 1.0.12 on Minecraft 1.20.1 Forge.
2. Open a crafting plan / submit a craft.
3. Craft fails to start; chat shows the `NoSuchMethodError`.

## Logs

`versions/1.20.1-forge/run/logs/debug.log` (excerpt above). Full stack is swallowed by the chat reporter, so only the message (not the trace) is logged.

## Blocker

Tracked upstream at https://github.com/vcwdfca/AE2CraftingTree — until the Crafting Tree mod stops crashing on craft start on 1.20.1 Forge, the TTC-in-tree feature can't be verified there.

**Comment by cTux** [comment]
## Update: mitigation + what to verify before closing

**Current state:** the Crafting Tree mod (`a1RwDz90`, AE2: Crafting Tree Refreshed) is now **disabled only for the `1.20.1-forge` run profile** (`scripts/run-client.ps1:19` and `scripts/run-client.sh:42`). Fabric 1.20.1 and both NeoForge targets keep it, since those loaders work. This unblocks crafting on 1.20.1 Forge by not pulling the broken jar; it does **not** fix the underlying mod bug.

The root cause stands: every 1.20.1-Forge build of `ae2ct` ships mixin classes compiled for Java 17 (class version 61), which Forge 1.20.1's bundled Mixin refuses (it only accepts up to class version 52 / Java 8). So there is no version of the mod to pin — freezing won't help until upstream recompiles the mixins for Java 8 (or Forge bumps its Mixin).

### Verification checklist before re-enabling / closing

When we want to turn the mod back on for 1.20.1 Forge (new fixed build, or a Forge version with a newer Mixin), verify all of:

1. **Mixin class version** — the resolved `ae2ct-*.jar` must have `AE2CraftingPlanSummary` (and the other `com.vcwdfca.ae2ct.mixin` / `com.neuvillette.ae2ct.mixin` classes) compiled for Java ≤ 8. Quick check: `javap -v ...AE2CraftingPlanSummary.class | grep "major version"` must be `52`, not `61`. Or, after a run, the debug log must **not** contain `Class version 61 required is higher than the class version supported by the current version of Mixin`.
2. **Run `run-1.20.1-Forge.bat`** and open a crafting plan / submit any craft.
3. **No craft failure** — `debug.log` must not show `Failed to start crafting job.` and chat must not show `NoSuchMethodError` on `FriendlyByteBuf.m_130130_` (`writeVarInt`).
4. **Crafting Tree window opens** and the in-tree TTC badges render (the feature this issue was blocking).
5. **Mixin applied cleanly** — debug log shows the `ae2ct` mixin mixed into `appeng.menu.me.crafting.CraftingPlanSummary` with no class-version warning.

If (1) fails, do not re-enable — it will just reproduce this issue. If all five pass, the issue is gone and we can re-add `a1RwDz90` to the `1.20.1-forge` profile.

**Comment by cTux** [comment]
The current Forge artifacts pass craft submission and Crafting Tree UI verification, so the TTC-in-tree blocker is resolved for the tested graphs.

- Prepared compatible client: Forge `47.4.10`, AE2 `15.4.10`, Crafting Tree Refreshed `1.0.1`; all 26 automated scenarios passed.
- Project Infinity 0.1 / `0.0.51.3 HOTFIX`: Forge `47.4.20`, AE2 `15.4.10`, original `ae2ct-1.20.1-1.1.1.jar`; the AdvancedAE craft and Crafting Tree UI scenarios passed.
- The tree opens through its toolbar button. Screenshots show node TTC and the full TTC/details/reset tooltip. Neither final log contains `Failed to start crafting job`, `NoSuchMethodError`, or a mixin application failure. Both clients exited.

Correction to the earlier comment: a class-version diagnostic alone did not establish that Forge refused the mixin. The claim that every Java 17 Crafting Tree artifact is unusable on Forge was too broad. Successful execution of these actual artifacts is stronger evidence; this does not claim to repair or reproduce every historical development mapping combination from the original report.

Closing as verified on the current graphs. The new regression coverage is in #191 at tested code commit `94b105f`; the final documentation commit records the results. Local archives: prepared `20260902T152335Z-advancedae-tree` and pack `20260902T155211Z-advancedae-tree`.
